# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AskDeveloper Podcast
email: your-email@domain.com
description: "Podcast for Egyptian and Arabic-speaking developers"
baseurl: "/askdeveloper-site" # the subpath of your site, e.g. /blog
url: "http://amreldib.com" # the base hostname & protocol for your site
twitter_username: AmrEldib
github_username:  AmrEldib

# Build settings
markdown: kramdown
